-- 宿舍服务平台基础表结构。
-- 范围：原有 20 张表，加上已经确认的 5 个字段。
-- 明确排除：D_Student.Balance 和 v2 方案中的所有扩展表。

CREATE TABLE D_College (
    College_ID NUMBER(10) CONSTRAINT PK_D_COLLEGE PRIMARY KEY,
    College_Name VARCHAR2(100) NOT NULL,
    Counselor_Name VARCHAR2(50),
    Contact_Phone VARCHAR2(20)
);

CREATE TABLE D_Building (
    Building_ID NUMBER(10) CONSTRAINT PK_D_BUILDING PRIMARY KEY,
    Building_Name VARCHAR2(50) NOT NULL,
    Building_Type VARCHAR2(20) NOT NULL,
    Total_Floors NUMBER(3)
);

CREATE TABLE D_Admin (
    Admin_ID VARCHAR2(20) CONSTRAINT PK_D_ADMIN PRIMARY KEY,
    Admin_Name VARCHAR2(50) NOT NULL,
    Phone VARCHAR2(20),
    Role_Level VARCHAR2(20) NOT NULL,
    Building_ID NUMBER(10),
    CONSTRAINT FK_D_ADMIN_BUILDING
        FOREIGN KEY (Building_ID) REFERENCES D_Building (Building_ID)
);

CREATE TABLE D_Major (
    Major_ID NUMBER(10) CONSTRAINT PK_D_MAJOR PRIMARY KEY,
    College_ID NUMBER(10),
    Major_Name VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_D_MAJOR_COLLEGE
        FOREIGN KEY (College_ID) REFERENCES D_College (College_ID)
);

CREATE TABLE D_Room (
    Room_ID NUMBER(10) CONSTRAINT PK_D_ROOM PRIMARY KEY,
    Building_ID NUMBER(10),
    Room_Number VARCHAR2(20) NOT NULL,
    Capacity NUMBER(2) DEFAULT 4,
    Occupancy NUMBER(2) DEFAULT 0,
    Power_Status VARCHAR2(10) DEFAULT '正常' NOT NULL,
    CONSTRAINT CK_D_ROOM_POWER_STATUS
        CHECK (Power_Status IN ('正常', '断电')),
    CONSTRAINT FK_D_ROOM_BUILDING
        FOREIGN KEY (Building_ID) REFERENCES D_Building (Building_ID)
);

CREATE TABLE D_Notice (
    Notice_ID NUMBER(10) CONSTRAINT PK_D_NOTICE PRIMARY KEY,
    Admin_ID VARCHAR2(20),
    Title VARCHAR2(100) NOT NULL,
    Content VARCHAR2(1000) NOT NULL,
    Publish_Time DATE NOT NULL,
    CONSTRAINT FK_D_NOTICE_ADMIN
        FOREIGN KEY (Admin_ID) REFERENCES D_Admin (Admin_ID)
);

CREATE TABLE D_Visitor_Log (
    Visitor_ID NUMBER(10) CONSTRAINT PK_D_VISITOR_LOG PRIMARY KEY,
    Building_ID NUMBER(10),
    Visitor_Name VARCHAR2(50) NOT NULL,
    Visit_Reason VARCHAR2(200) NOT NULL,
    Entry_Time DATE NOT NULL,
    Leave_Time DATE,
    CONSTRAINT FK_D_VISITOR_LOG_BUILDING
        FOREIGN KEY (Building_ID) REFERENCES D_Building (Building_ID)
);

CREATE TABLE D_Student (
    Student_ID VARCHAR2(20) CONSTRAINT PK_D_STUDENT PRIMARY KEY,
    Name VARCHAR2(50) NOT NULL,
    Gender VARCHAR2(10),
    Major_ID NUMBER(10),
    Phone VARCHAR2(20),
    CONSTRAINT FK_D_STUDENT_MAJOR
        FOREIGN KEY (Major_ID) REFERENCES D_Major (Major_ID)
);

CREATE TABLE D_Asset (
    Asset_ID NUMBER(10) CONSTRAINT PK_D_ASSET PRIMARY KEY,
    Room_ID NUMBER(10),
    Asset_Name VARCHAR2(50) NOT NULL,
    Quantity NUMBER(3) DEFAULT 1,
    Status VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_D_ASSET_ROOM
        FOREIGN KEY (Room_ID) REFERENCES D_Room (Room_ID)
);

CREATE TABLE D_Utility_Fee (
    Fee_ID NUMBER(10) CONSTRAINT PK_D_UTILITY_FEE PRIMARY KEY,
    Room_ID NUMBER(10),
    Year_Month VARCHAR2(10) NOT NULL,
    Water_Fee NUMBER(8, 2),
    Power_Fee NUMBER(8, 2),
    Is_Paid VARCHAR2(10) DEFAULT '否',
    CONSTRAINT FK_D_UTILITY_FEE_ROOM
        FOREIGN KEY (Room_ID) REFERENCES D_Room (Room_ID)
);

CREATE TABLE D_Hygiene_Record (
    Record_ID NUMBER(10) CONSTRAINT PK_D_HYGIENE_RECORD PRIMARY KEY,
    Room_ID NUMBER(10),
    Check_Date DATE NOT NULL,
    Score NUMBER(4, 1) NOT NULL,
    Inspector_ID VARCHAR2(20),
    CONSTRAINT FK_D_HYGIENE_RECORD_ROOM
        FOREIGN KEY (Room_ID) REFERENCES D_Room (Room_ID),
    CONSTRAINT FK_D_HYGIENE_RECORD_ADMIN
        FOREIGN KEY (Inspector_ID) REFERENCES D_Admin (Admin_ID)
);

CREATE TABLE D_Water_Order (
    Order_ID NUMBER(10) CONSTRAINT PK_D_WATER_ORDER PRIMARY KEY,
    Room_ID NUMBER(10),
    Order_Time DATE NOT NULL,
    Quantity NUMBER(2) DEFAULT 1,
    Status VARCHAR2(20) DEFAULT '未送达',
    CONSTRAINT FK_D_WATER_ORDER_ROOM
        FOREIGN KEY (Room_ID) REFERENCES D_Room (Room_ID)
);

CREATE TABLE D_Bed_Allocation (
    Allocation_ID NUMBER(10) CONSTRAINT PK_D_BED_ALLOCATION PRIMARY KEY,
    Student_ID VARCHAR2(20),
    Room_ID NUMBER(10),
    CheckIn_Date DATE NOT NULL,
    CheckOut_Date DATE,
    CONSTRAINT FK_D_BED_ALLOCATION_STUDENT
        FOREIGN KEY (Student_ID) REFERENCES D_Student (Student_ID),
    CONSTRAINT FK_D_BED_ALLOCATION_ROOM
        FOREIGN KEY (Room_ID) REFERENCES D_Room (Room_ID)
);

CREATE TABLE D_Repair_Ticket (
    Ticket_ID NUMBER(10) CONSTRAINT PK_D_REPAIR_TICKET PRIMARY KEY,
    Student_ID VARCHAR2(20),
    Room_ID NUMBER(10),
    Issue_Desc VARCHAR2(500) NOT NULL,
    Submit_Time DATE NOT NULL,
    Status VARCHAR2(20) DEFAULT '待处理',
    SLA_Level VARCHAR2(10) DEFAULT '普通' NOT NULL,
    Deadline DATE,
    Assigned_To VARCHAR2(20),
    CONSTRAINT CK_D_REPAIR_TICKET_SLA_LEVEL
        CHECK (SLA_Level IN ('普通', '紧急')),
    CONSTRAINT FK_D_REPAIR_TICKET_STUDENT
        FOREIGN KEY (Student_ID) REFERENCES D_Student (Student_ID),
    CONSTRAINT FK_D_REPAIR_TICKET_ROOM
        FOREIGN KEY (Room_ID) REFERENCES D_Room (Room_ID),
    CONSTRAINT FK_D_REPAIR_TICKET_ASSIGNED_ADMIN
        FOREIGN KEY (Assigned_To) REFERENCES D_Admin (Admin_ID)
);

CREATE TABLE D_Repair_Log (
    Log_ID NUMBER(10) CONSTRAINT PK_D_REPAIR_LOG PRIMARY KEY,
    Ticket_ID NUMBER(10),
    Admin_ID VARCHAR2(20),
    Process_Desc VARCHAR2(500),
    Resolve_Time DATE NOT NULL,
    CONSTRAINT UK_D_REPAIR_LOG_TICKET UNIQUE (Ticket_ID),
    CONSTRAINT FK_D_REPAIR_LOG_TICKET
        FOREIGN KEY (Ticket_ID) REFERENCES D_Repair_Ticket (Ticket_ID),
    CONSTRAINT FK_D_REPAIR_LOG_ADMIN
        FOREIGN KEY (Admin_ID) REFERENCES D_Admin (Admin_ID)
);

CREATE TABLE D_Late_Entry (
    Record_ID NUMBER(10) CONSTRAINT PK_D_LATE_ENTRY PRIMARY KEY,
    Student_ID VARCHAR2(20),
    Return_Time DATE NOT NULL,
    Reason VARCHAR2(200),
    CONSTRAINT FK_D_LATE_ENTRY_STUDENT
        FOREIGN KEY (Student_ID) REFERENCES D_Student (Student_ID)
);

CREATE TABLE D_Access_Log (
    Log_ID NUMBER(10) CONSTRAINT PK_D_ACCESS_LOG PRIMARY KEY,
    Student_ID VARCHAR2(20),
    Building_ID NUMBER(10),
    Swipe_Time DATE NOT NULL,
    Direction VARCHAR2(10) NOT NULL,
    CONSTRAINT FK_D_ACCESS_LOG_STUDENT
        FOREIGN KEY (Student_ID) REFERENCES D_Student (Student_ID),
    CONSTRAINT FK_D_ACCESS_LOG_BUILDING
        FOREIGN KEY (Building_ID) REFERENCES D_Building (Building_ID)
);

CREATE TABLE D_Leave_Application (
    Apply_ID NUMBER(10) CONSTRAINT PK_D_LEAVE_APPLICATION PRIMARY KEY,
    Student_ID VARCHAR2(20),
    Leave_Date DATE NOT NULL,
    Return_Date DATE NOT NULL,
    Destination VARCHAR2(200) NOT NULL,
    Status VARCHAR2(20) DEFAULT '待批',
    CONSTRAINT FK_D_LEAVE_APPLICATION_STUDENT
        FOREIGN KEY (Student_ID) REFERENCES D_Student (Student_ID)
);

CREATE TABLE D_Parcel_Record (
    Parcel_ID NUMBER(10) CONSTRAINT PK_D_PARCEL_RECORD PRIMARY KEY,
    Student_ID VARCHAR2(20),
    Arrive_Time DATE NOT NULL,
    Pickup_Time DATE,
    Courier_Company VARCHAR2(50),
    CONSTRAINT FK_D_PARCEL_RECORD_STUDENT
        FOREIGN KEY (Student_ID) REFERENCES D_Student (Student_ID)
);

CREATE TABLE D_Violation_Record (
    Record_ID NUMBER(10) CONSTRAINT PK_D_VIOLATION_RECORD PRIMARY KEY,
    Student_ID VARCHAR2(20),
    Room_ID NUMBER(10),
    Vio_Type VARCHAR2(50) NOT NULL,
    Vio_Date DATE NOT NULL,
    Penalty VARCHAR2(100),
    CONSTRAINT FK_D_VIOLATION_RECORD_STUDENT
        FOREIGN KEY (Student_ID) REFERENCES D_Student (Student_ID),
    CONSTRAINT FK_D_VIOLATION_RECORD_ROOM
        FOREIGN KEY (Room_ID) REFERENCES D_Room (Room_ID)
);
