-- 扩展表结构检查脚本。
-- 请在同一个 Oracle schema 中先执行
-- ddl/foundation/001_create_tables.sql 和 ddl/extensions/010_extension_tables.sql。

-- 1. 期望扩展表数量为 25 张（含迁移 029 新增的 D_Asset_Repair / D_Asset_Warning）。
SELECT COUNT(*) AS ACTUAL_EXTENSION_TABLE_COUNT
FROM USER_TABLES
WHERE TABLE_NAME IN (
    'D_FEE_DETAIL', 'D_WALLET_ACCOUNT', 'D_WALLET_LOG',
    'D_FEE_DEDUCTION_ATTEMPT', 'D_CREDIT_ACCOUNT', 'D_CREDIT_LOG',
    'D_SHARED_ITEM', 'D_ITEM_LOAN', 'D_FACILITY', 'D_FACILITY_BOOKING',
    'D_CLEANING_TASK', 'D_REPAIR_MATERIAL', 'D_REPAIR_MATERIAL_USAGE',
    'D_REPAIR_ATTACHMENT', 'D_USER_ACCOUNT', 'D_NOTIFICATION',
    'D_VISITOR_AUTHORIZATION', 'D_AUDIT_EVENT', 'D_ROOM_VOTE',
    'D_ROOM_VOTE_RESPONSE', 'D_CHECKOUT_LOG', 'D_NOTICE_DISPLAY',
    'D_HYGIENE_COMMENT',
    'D_ASSET_REPAIR', 'D_ASSET_WARNING'
);

-- 2. 检查缺失的扩展表：本查询应无返回行。
WITH EXPECTED_TABLES (TABLE_NAME) AS (
    SELECT 'D_FEE_DETAIL' FROM DUAL UNION ALL
    SELECT 'D_WALLET_ACCOUNT' FROM DUAL UNION ALL
    SELECT 'D_WALLET_LOG' FROM DUAL UNION ALL
    SELECT 'D_FEE_DEDUCTION_ATTEMPT' FROM DUAL UNION ALL
    SELECT 'D_CREDIT_ACCOUNT' FROM DUAL UNION ALL
    SELECT 'D_CREDIT_LOG' FROM DUAL UNION ALL
    SELECT 'D_SHARED_ITEM' FROM DUAL UNION ALL
    SELECT 'D_ITEM_LOAN' FROM DUAL UNION ALL
    SELECT 'D_FACILITY' FROM DUAL UNION ALL
    SELECT 'D_FACILITY_BOOKING' FROM DUAL UNION ALL
    SELECT 'D_CLEANING_TASK' FROM DUAL UNION ALL
    SELECT 'D_REPAIR_MATERIAL' FROM DUAL UNION ALL
    SELECT 'D_REPAIR_MATERIAL_USAGE' FROM DUAL UNION ALL
    SELECT 'D_REPAIR_ATTACHMENT' FROM DUAL UNION ALL
    SELECT 'D_USER_ACCOUNT' FROM DUAL UNION ALL
    SELECT 'D_NOTIFICATION' FROM DUAL UNION ALL
    SELECT 'D_VISITOR_AUTHORIZATION' FROM DUAL UNION ALL
    SELECT 'D_AUDIT_EVENT' FROM DUAL UNION ALL
    SELECT 'D_ROOM_VOTE' FROM DUAL UNION ALL
    SELECT 'D_ROOM_VOTE_RESPONSE' FROM DUAL UNION ALL
    SELECT 'D_CHECKOUT_LOG' FROM DUAL UNION ALL
    SELECT 'D_NOTICE_DISPLAY' FROM DUAL UNION ALL
    SELECT 'D_HYGIENE_COMMENT' FROM DUAL UNION ALL
    SELECT 'D_ASSET_REPAIR' FROM DUAL UNION ALL
    SELECT 'D_ASSET_WARNING' FROM DUAL
)
SELECT TABLE_NAME
FROM EXPECTED_TABLES
MINUS
SELECT TABLE_NAME
FROM USER_TABLES;

-- 3. 检查范围裁决中明确排除的表：本查询应无返回行。
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN (
    'D_FACILITY_USAGE', 'D_REPAIR_SLA_EVENT', 'D_ROLE',
    'D_NOTIFICATION_RECIPIENT', 'D_FEE_ADJUSTMENT'
);

-- 4. 检查关键字段及其可空性，确认关键关联路径完整且必要字段为 NOT NULL。
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION,
       DATA_SCALE, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME IN (
    'D_FEE_DETAIL', 'D_WALLET_ACCOUNT', 'D_WALLET_LOG',
    'D_FEE_DEDUCTION_ATTEMPT', 'D_CREDIT_ACCOUNT', 'D_CREDIT_LOG',
    'D_SHARED_ITEM', 'D_ITEM_LOAN', 'D_FACILITY', 'D_FACILITY_BOOKING',
    'D_CLEANING_TASK', 'D_REPAIR_MATERIAL', 'D_REPAIR_MATERIAL_USAGE',
    'D_REPAIR_ATTACHMENT', 'D_USER_ACCOUNT', 'D_NOTIFICATION',
    'D_VISITOR_AUTHORIZATION', 'D_AUDIT_EVENT', 'D_ROOM_VOTE',
    'D_ROOM_VOTE_RESPONSE', 'D_CHECKOUT_LOG', 'D_NOTICE_DISPLAY',
    'D_HYGIENE_COMMENT',
    'D_ASSET_REPAIR', 'D_ASSET_WARNING'
)
AND COLUMN_NAME IN (
    'DETAIL_ID', 'FEE_ID', 'STUDENT_ID', 'ROOM_ID', 'WATER_SHARE',
    'POWER_SHARE', 'STAY_DAYS', 'TOTAL_DAYS', 'BILL_TYPE', 'IS_PAID',
    'BALANCE', 'LOG_ID', 'AMOUNT', 'TRANSACTION_TYPE', 'BEFORE_BALANCE',
    'AFTER_BALANCE', 'IDEMPOTENCY_KEY', 'ATTEMPT_ID', 'ATTEMPT_NO',
    'ATTEMPT_TIME', 'RESULT', 'CURRENT_SCORE', 'UPDATED_TIME',
    'SCORE_CHANGE', 'REASON', 'EVENT_KEY', 'ITEM_ID', 'ITEM_NAME',
    'BUILDING_ID', 'TOTAL_QTY', 'AVAILABLE_QTY', 'LOAN_ID', 'BORROW_TIME',
    'DUE_TIME', 'RETURN_TIME', 'FACILITY_ID', 'FACILITY_CODE',
    'FACILITY_TYPE', 'BOOKING_ID', 'CREATE_TIME', 'START_TIME', 'END_TIME',
    'TRIGGER_COUNT', 'STATUS', 'COMPLETE_TIME', 'MATERIAL_ID',
    'MATERIAL_NAME', 'UNIT', 'STOCK_QTY', 'USAGE_ID', 'TICKET_ID',
    'QUANTITY', 'USE_TIME', 'ATTACHMENT_ID', 'STORAGE_REF', 'ORIGINAL_NAME',
    'CONTENT_TYPE', 'FILE_SIZE', 'ACCOUNT_ID', 'LOGIN_NAME', 'PASSWORD_HASH',
    'ACCOUNT_STATUS', 'ADMIN_ID', 'NOTIFICATION_ID', 'RECIPIENT_ACCOUNT_ID',
    'TITLE', 'CONTENT', 'NOTIFICATION_TYPE', 'READ_TIME', 'AUTHORIZATION_ID',
    'VISITOR_NAME', 'VISIT_REASON', 'AUTHORIZATION_TOKEN', 'EXPIRES_TIME',
    'AUDIT_ID', 'ACTOR_ACCOUNT_ID', 'EVENT_TYPE', 'TARGET_TYPE', 'TARGET_ID',
    'EVENT_TIME', 'VOTE_ID', 'INITIATOR_STUDENT_ID', 'TOPIC', 'DEADLINE',
    'ELIGIBLE_COUNT', 'VOTE_TIME', 'CHOICE', 'REQUEST_TIME', 'RESULT_TIME',
    'FEE_CHECK', 'ITEM_CHECK', 'REJECT_REASON', 'NOTICE_ID', 'IS_PINNED',
    'PIN_TIME', 'RECORD_ID', 'COMMENT',
    'LINK_ID', 'ASSET_ID', 'WARNING_ID', 'NOTE', 'HANDLE_ACTION',
    'HANDLE_TIME', 'HANDLED'
)
ORDER BY TABLE_NAME, COLUMN_ID;

-- 5. 检查扩展表约束是否全部启用且已验证。
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS, VALIDATED
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN (
    'D_FEE_DETAIL', 'D_WALLET_ACCOUNT', 'D_WALLET_LOG',
    'D_FEE_DEDUCTION_ATTEMPT', 'D_CREDIT_ACCOUNT', 'D_CREDIT_LOG',
    'D_SHARED_ITEM', 'D_ITEM_LOAN', 'D_FACILITY', 'D_FACILITY_BOOKING',
    'D_CLEANING_TASK', 'D_REPAIR_MATERIAL', 'D_REPAIR_MATERIAL_USAGE',
    'D_REPAIR_ATTACHMENT', 'D_USER_ACCOUNT', 'D_NOTIFICATION',
    'D_VISITOR_AUTHORIZATION', 'D_AUDIT_EVENT', 'D_ROOM_VOTE',
    'D_ROOM_VOTE_RESPONSE', 'D_CHECKOUT_LOG', 'D_NOTICE_DISPLAY',
    'D_HYGIENE_COMMENT',
    'D_ASSET_REPAIR', 'D_ASSET_WARNING'
)
AND (STATUS <> 'ENABLED' OR VALIDATED <> 'VALIDATED')
ORDER BY TABLE_NAME, CONSTRAINT_NAME;

-- 6. 按约束类型统计扩展表约束数量。
SELECT CONSTRAINT_TYPE, COUNT(*) AS CONSTRAINT_COUNT
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN (
    'D_FEE_DETAIL', 'D_WALLET_ACCOUNT', 'D_WALLET_LOG',
    'D_FEE_DEDUCTION_ATTEMPT', 'D_CREDIT_ACCOUNT', 'D_CREDIT_LOG',
    'D_SHARED_ITEM', 'D_ITEM_LOAN', 'D_FACILITY', 'D_FACILITY_BOOKING',
    'D_CLEANING_TASK', 'D_REPAIR_MATERIAL', 'D_REPAIR_MATERIAL_USAGE',
    'D_REPAIR_ATTACHMENT', 'D_USER_ACCOUNT', 'D_NOTIFICATION',
    'D_VISITOR_AUTHORIZATION', 'D_AUDIT_EVENT', 'D_ROOM_VOTE',
    'D_ROOM_VOTE_RESPONSE', 'D_CHECKOUT_LOG', 'D_NOTICE_DISPLAY',
    'D_HYGIENE_COMMENT',
    'D_ASSET_REPAIR', 'D_ASSET_WARNING'
)
GROUP BY CONSTRAINT_TYPE
ORDER BY CONSTRAINT_TYPE;

-- 7. 检查本方案中明确采用的复合主键和复合唯一约束。
SELECT CONSTRAINT_NAME, TABLE_NAME, POSITION, COLUMN_NAME
FROM USER_CONS_COLUMNS
WHERE CONSTRAINT_NAME IN (
    'PK_D_ROOM_VOTE_RESP', 'UK_D_FEE_DED_ATT', 'UK_D_FACILITY_CODE',
    'UK_D_CLEANING_TRIGGER', 'UK_D_FEE_DETAIL'
)
ORDER BY CONSTRAINT_NAME, POSITION;

-- 8. 检查扩展表外键及其引用目标。
SELECT CHILD_CONSTRAINT.CONSTRAINT_NAME,
       CHILD.TABLE_NAME AS CHILD_TABLE,
       CHILD.COLUMN_NAME AS CHILD_COLUMN,
       PARENT.TABLE_NAME AS PARENT_TABLE,
       PARENT.COLUMN_NAME AS PARENT_COLUMN
FROM USER_CONS_COLUMNS CHILD
JOIN USER_CONSTRAINTS CHILD_CONSTRAINT
  ON CHILD.CONSTRAINT_NAME = CHILD_CONSTRAINT.CONSTRAINT_NAME
 AND CHILD.OWNER = CHILD_CONSTRAINT.OWNER
JOIN USER_CONS_COLUMNS PARENT
  ON CHILD_CONSTRAINT.R_CONSTRAINT_NAME = PARENT.CONSTRAINT_NAME
 AND CHILD_CONSTRAINT.R_OWNER = PARENT.OWNER
 AND CHILD.POSITION = PARENT.POSITION
WHERE CHILD_CONSTRAINT.CONSTRAINT_TYPE = 'R'
  AND CHILD.TABLE_NAME IN (
      'D_FEE_DETAIL', 'D_WALLET_ACCOUNT', 'D_WALLET_LOG',
      'D_FEE_DEDUCTION_ATTEMPT', 'D_CREDIT_ACCOUNT', 'D_CREDIT_LOG',
      'D_SHARED_ITEM', 'D_ITEM_LOAN', 'D_FACILITY', 'D_FACILITY_BOOKING',
      'D_CLEANING_TASK', 'D_REPAIR_MATERIAL', 'D_REPAIR_MATERIAL_USAGE',
      'D_REPAIR_ATTACHMENT', 'D_USER_ACCOUNT', 'D_NOTIFICATION',
      'D_VISITOR_AUTHORIZATION', 'D_AUDIT_EVENT', 'D_ROOM_VOTE',
      'D_ROOM_VOTE_RESPONSE', 'D_CHECKOUT_LOG', 'D_NOTICE_DISPLAY',
      'D_HYGIENE_COMMENT',
      'D_ASSET_REPAIR', 'D_ASSET_WARNING'
  )
ORDER BY CHILD.TABLE_NAME, CHILD_CONSTRAINT.CONSTRAINT_NAME, CHILD.POSITION;

-- 9. 检查账号身份互斥绑定约束、公告置顶约束和通知类型枚举约束是否存在
--    （CK_D_NOTIFICATION_TYPE 来自迁移脚本 011）。
SELECT CONSTRAINT_NAME, SEARCH_CONDITION_VC
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME IN ('CK_D_USER_STATUS', 'CK_D_USER_IDENTITY',
                          'CK_D_NOTICE_DISPLAY_PIN', 'CK_D_NOTIFICATION_TYPE')
ORDER BY CONSTRAINT_NAME;

-- 10. 检查部分唯一索引存在且有效（退宿清算与设施预约并发兜底）。
SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS, STATUS
FROM USER_INDEXES
WHERE INDEX_NAME IN ('UK_D_CHECKOUT_ACTIVE', 'UK_D_FACILITY_BOOK_ACTIVE')
ORDER BY INDEX_NAME;

-- 11. 检查迁移 012 的通知主键序列、触发器和收件人索引（D_Notification 落库依赖）。
SELECT SEQUENCE_NAME FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'SEQ_D_NOTIFICATION_ID';
SELECT TRIGGER_NAME, STATUS FROM USER_TRIGGERS
WHERE TRIGGER_NAME = 'TRG_D_NOTIFICATION_ID_BI';
SELECT INDEX_NAME, TABLE_NAME, STATUS FROM USER_INDEXES
WHERE INDEX_NAME = 'IDX_D_NOTIFICATION_RECIPIENT';

-- 12. 检查迁移 014 的信用分序列、触发器、稳定排序索引和字符长度语义。
SELECT SEQUENCE_NAME
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'SEQ_D_CREDIT_LOG_ID';

SELECT TRIGGER_NAME, STATUS
FROM USER_TRIGGERS
WHERE TRIGGER_NAME = 'TRG_D_CREDIT_LOG_ID_BI';

SELECT INDEX_NAME, COLUMN_POSITION, COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE INDEX_NAME = 'IDX_D_CREDIT_LOG_STUDENT_TIME'
ORDER BY COLUMN_POSITION;

SELECT COLUMN_NAME, CHAR_USED, CHAR_LENGTH
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'D_CREDIT_LOG'
  AND ((COLUMN_NAME = 'REASON' AND CHAR_USED = 'C' AND CHAR_LENGTH = 200)
    OR (COLUMN_NAME = 'EVENT_KEY' AND CHAR_USED = 'C' AND CHAR_LENGTH = 100))
ORDER BY COLUMN_NAME;

-- 13. 检查 010 新增的主键序列与触发器（D_Facility / D_Notice / D_Notice_Display）。
--     每段 SELECT 均应返回 1 行；缺任意一个对象说明 010 未完整执行。
SELECT SEQUENCE_NAME FROM USER_SEQUENCES
WHERE SEQUENCE_NAME IN ('SEQ_D_FACILITY_ID', 'SEQ_D_NOTICE_ID', 'SEQ_D_NOTICE_DISPLAY_PK')
ORDER BY SEQUENCE_NAME;

SELECT TRIGGER_NAME, STATUS FROM USER_TRIGGERS
WHERE TRIGGER_NAME IN ('TRG_D_FACILITY_ID_BI', 'TRG_D_NOTICE_ID_BI', 'TRG_D_NOTICE_DISPLAY_PK_BI')
ORDER BY TRIGGER_NAME;

-- 14. 检查迁移 016 的 D_Room 新增列（Floor / Status，C-022 裁决）。
--     每列应返回 1 行；STATUS 列同时带约束校验。
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'D_ROOM'
  AND COLUMN_NAME IN ('FLOOR', 'STATUS')
ORDER BY COLUMN_NAME;

SELECT CONSTRAINT_NAME, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'D_ROOM'
  AND CONSTRAINT_NAME = 'CK_D_ROOM_STATUS';

-- 15. 检查迁移 017 的 D_Leave_Application 新增列（Reason，C-023 裁决）。
--     应返回 1 行；CHAR_USED='C'、CHAR_LENGTH=200（实例为 BYTE 语义，须显式
--     CHAR 长度，同 013 迁移先例）。
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE,
       CHAR_USED, CHAR_LENGTH
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'D_LEAVE_APPLICATION'
  AND COLUMN_NAME = 'REASON';

-- 16. 检查迁移 018 的 D_Student 新增列（Email，C-027 确认）。
--     应返回 1 行；NULLABLE='Y'、CHAR_USED='C'、CHAR_LENGTH=200（实例为
--     BYTE 语义，须显式 CHAR 长度，同 013/017 迁移先例）。
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE,
       CHAR_USED, CHAR_LENGTH
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'D_STUDENT'
  AND COLUMN_NAME = 'EMAIL';

-- 17. 检查迁移 019 的幂等键列与唯一索引（D_Item_Loan / D_Repair_Material_Usage，
--     C-030 确认，难点④ 幂等设计落库）。应返回 2 行；NULLABLE='Y'、
--     CHAR_USED='C'、CHAR_LENGTH=100（实例为 BYTE 语义，须显式 CHAR 长度，
--     同 013/014/017/018 迁移先例）。
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE,
       CHAR_USED, CHAR_LENGTH
FROM USER_TAB_COLUMNS
WHERE (TABLE_NAME = 'D_ITEM_LOAN' AND COLUMN_NAME = 'IDEMPOTENCY_KEY')
   OR (TABLE_NAME = 'D_REPAIR_MATERIAL_USAGE' AND COLUMN_NAME = 'IDEMPOTENCY_KEY');

-- 17b. 幂等键唯一索引（并发重放兜底：撞唯一索引触发 SAVEPOINT 回滚与内容比对）。
--     应返回 2 行；UNIQUENESS='UNIQUE'、STATUS='VALID'。
SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS, STATUS
FROM USER_INDEXES
WHERE INDEX_NAME IN ('UK_D_ITEM_LOAN_IDEM', 'UK_D_REPAIR_MAT_USE_IDEM');

-- 18. 检查迁移 020 的主键序列与触发器（D_Repair_Ticket / D_Repair_Attachment /
--     D_Late_Entry / D_Hygiene_Record / D_Room，C-031/C-032 裁决：为首次写入的
--     4 张表补主键生成，并消除 D_Room 的 ORA-01400 地雷）。
--     每段 SELECT 均应返回 5 行；缺任意一个对象说明迁移 020 未完整执行。
SELECT SEQUENCE_NAME FROM USER_SEQUENCES
WHERE SEQUENCE_NAME IN (
    'SEQ_D_REPAIR_TICKET_ID',
    'SEQ_D_REPAIR_ATTACHMENT_ID',
    'SEQ_D_LATE_ENTRY_ID',
    'SEQ_D_HYGIENE_RECORD_ID',
    'SEQ_D_ROOM_ID')
ORDER BY SEQUENCE_NAME;

SELECT TRIGGER_NAME, STATUS FROM USER_TRIGGERS
WHERE TRIGGER_NAME IN (
    'TRG_D_REPAIR_TICKET_ID_BI',
    'TRG_D_REPAIR_ATTACHMENT_ID_BI',
    'TRG_D_LATE_ENTRY_ID_BI',
    'TRG_D_HYGIENE_RECORD_ID_BI',
    'TRG_D_ROOM_ID_BI')
ORDER BY TRIGGER_NAME;

-- 19. 检查迁移 021（难点⑤ SLA 派单 DDL，C-033/C-034 确认；枚举以 PRD 为准，
--     用户 2026-08-13 拍板）。
-- 19a. D_Repair_Ticket 新增列 Escalation_Time：应返回 1 行；NULLABLE='Y'
--      （NULL=未升级，防二次升级标记）。
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'D_REPAIR_TICKET'
  AND COLUMN_NAME = 'ESCALATION_TIME';

-- 19b. D_Repair_Log 新增列 Repair_Result：应返回 1 行；NULLABLE='Y'、
--      CHAR_USED='C'、CHAR_LENGTH=200（实例为 BYTE 语义，须显式 CHAR 长度，
--      同 013/017/018/019 迁移先例）。
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE,
       CHAR_USED, CHAR_LENGTH
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'D_REPAIR_LOG'
  AND COLUMN_NAME = 'REPAIR_RESULT';

-- 19c. D_Repair_Log 专用主键序列 SEQ_SLA_LOG（MAX(Log_ID)+1 起点对齐存量，
--      同 C-016/020 先例）：应返回 1 行。
SELECT SEQUENCE_NAME FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'SEQ_SLA_LOG';

-- 19d. 两个 CHECK 约束（状态集 待处理/已派单/已完成/已撤销；角色 楼长/维修员/
--      超级管理员，迁移 032 生效后纳入辅导员，无卫生检查员岗位）：各返回 1 行，
--      CONSTRAINT_TYPE='C'。值集含"辅导员"的专项检查见 §30（未应用 032 时 §30
--      返回 0 行为预期，§19d 仍应返回 1 行，不应误判迁移失败）。
--      ⚠️ Part C 依赖 PR #45 状态机改造完成后执行；未执行时本段返回 0 行
--      为预期，不应误判迁移失败。
SELECT TABLE_NAME, CONSTRAINT_NAME, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME IN ('CK_D_REPAIR_TICKET_STATUS', 'CK_D_ADMIN_ROLE')
ORDER BY CONSTRAINT_NAME;

-- 20. 检查迁移 024 的主键序列与触发器（D_Room_Vote / D_Visitor_Authorization /
--     D_Parcel_Record，安全社区三表，为首次写入补主键生成，消除 ORA-01400）。
--     每段 SELECT 均应返回 3 行；缺任意一个对象说明迁移 024 未完整执行。
SELECT SEQUENCE_NAME FROM USER_SEQUENCES
WHERE SEQUENCE_NAME IN (
    'SEQ_D_ROOM_VOTE_ID',
    'SEQ_D_VISITOR_AUTH_ID',
    'SEQ_D_PARCEL_RECORD_ID')
ORDER BY SEQUENCE_NAME;

SELECT TRIGGER_NAME, STATUS FROM USER_TRIGGERS
WHERE TRIGGER_NAME IN (
    'TRG_D_ROOM_VOTE_ID_BI',
    'TRG_D_VISITOR_AUTH_ID_BI',
    'TRG_D_PARCEL_RECORD_ID_BI')
ORDER BY TRIGGER_NAME;

-- 21. 检查迁移 026 的 D_Utility_Fee 主键序列与触发器（PR #58：缴费/账单端点
--     落库依赖，DORM-19 录账单时 EF 以 NULL 主键写入、由触发器回填）。
--     每段 SELECT 均应返回 1 行；缺任意一个对象说明 026 未执行。
SELECT SEQUENCE_NAME FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'SEQ_D_UTILITY_FEE_ID';

SELECT TRIGGER_NAME, STATUS FROM USER_TRIGGERS
WHERE TRIGGER_NAME = 'TRG_D_UTILITY_FEE_ID_BI';

-- 22. 检查迁移 013 的 D_Notification 字符长度语义（Title/Content 显式 CHAR）。
--     应返回 2 行；CHAR_USED='C'，Title CHAR_LENGTH=100，Content CHAR_LENGTH=1000。
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHAR_USED, CHAR_LENGTH
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'D_NOTIFICATION'
  AND COLUMN_NAME IN ('TITLE', 'CONTENT')
ORDER BY COLUMN_NAME;

-- 23. 检查迁移 022 的 D_Fee_Detail 唯一约束收紧（两入口互斥，IT-C10-004 并发兜底）。
--     应返回 2 行：UK_D_FEE_DETAIL，列序为 Fee_ID, Student_ID（无 Bill_Type）。
SELECT uc.CONSTRAINT_NAME, uic.COLUMN_NAME, uic.POSITION
FROM USER_CONSTRAINTS uc
JOIN USER_CONS_COLUMNS uic ON uc.CONSTRAINT_NAME = uic.CONSTRAINT_NAME
WHERE uc.TABLE_NAME = 'D_FEE_DETAIL'
  AND uc.CONSTRAINT_TYPE = 'U'
  AND uc.CONSTRAINT_NAME = 'UK_D_FEE_DETAIL'
ORDER BY uic.POSITION;

-- 24. 检查迁移 023 的 D_Room 唯一索引 + D_Bed_Allocation / D_Checkout_Log /
--     D_Leave_Application 主键序列与触发器（PR #49 一审整改，C-040 裁定）。
--     索引 1 行；序列 3 行；触发器 3 行。
SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS, STATUS
FROM USER_INDEXES
WHERE INDEX_NAME = 'UK_D_ROOM_BUILDING_NO';

SELECT SEQUENCE_NAME FROM USER_SEQUENCES
WHERE SEQUENCE_NAME IN (
    'SEQ_D_BED_ALLOCATION_ID',
    'SEQ_D_CHECKOUT_LOG_ID',
    'SEQ_D_LEAVE_APPLICATION_ID')
ORDER BY SEQUENCE_NAME;

SELECT TRIGGER_NAME, STATUS FROM USER_TRIGGERS
WHERE TRIGGER_NAME IN (
    'TRG_D_BED_ALLOCATION_ID_BI',
    'TRG_D_CHECKOUT_LOG_ID_BI',
    'TRG_D_LEAVE_APPLICATION_ID_BI')
ORDER BY TRIGGER_NAME;

-- 25. 检查迁移 025 的 D_Audit_Event.DETAILS + D_College / D_Major 主键序列与触发器
--     （PR #55 三审补充，审计详情与学院/专业写入依赖）。
--     DETAILS 1 行；序列 2 行；触发器 2 行。
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHAR_USED, CHAR_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'D_AUDIT_EVENT'
  AND COLUMN_NAME = 'DETAILS';

SELECT SEQUENCE_NAME FROM USER_SEQUENCES
WHERE SEQUENCE_NAME IN ('SEQ_D_COLLEGE_ID', 'SEQ_D_MAJOR_ID')
ORDER BY SEQUENCE_NAME;

SELECT TRIGGER_NAME, STATUS FROM USER_TRIGGERS
WHERE TRIGGER_NAME IN ('TRG_D_COLLEGE_ID_BI', 'TRG_D_MAJOR_ID_BI')
ORDER BY TRIGGER_NAME;

-- 26. 检查迁移 027 的 D_Admin.POST 列（AUTH-05 宿管岗位字段）。
--     应返回 1 行；NULLABLE='Y'，DATA_TYPE='VARCHAR2'。
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHAR_USED, CHAR_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'D_ADMIN'
  AND COLUMN_NAME = 'POST';

-- 27. 检查迁移 029（资产/共享物品/保洁主键生成器 + 扩展表 + description 列）。
--     本迁移补齐 D_Asset / D_Shared_Item / D_Cleaning_Task 主键生成（消除
--     ORA-01400），并新增 D_Asset_Repair / D_Asset_Warning 两张扩展表。
-- 27a. 主键序列：应返回 5 行；缺任意一个对象说明迁移 029 未完整执行。
SELECT SEQUENCE_NAME FROM USER_SEQUENCES
WHERE SEQUENCE_NAME IN (
    'SEQ_D_ASSET_ID',
    'SEQ_D_SHARED_ITEM_ID',
    'SEQ_D_CLEANING_TASK_ID',
    'SEQ_D_ASSET_REPAIR_ID',
    'SEQ_D_ASSET_WARNING_ID')
ORDER BY SEQUENCE_NAME;

-- 27b. 主键触发器：应返回 5 行；STATUS='ENABLED'。
SELECT TRIGGER_NAME, STATUS FROM USER_TRIGGERS
WHERE TRIGGER_NAME IN (
    'TRG_D_ASSET_ID_BI',
    'TRG_D_SHARED_ITEM_ID_BI',
    'TRG_D_CLEANING_TASK_ID_BI',
    'TRG_D_ASSET_REPAIR_ID_BI',
    'TRG_D_ASSET_WARNING_ID_BI')
ORDER BY TRIGGER_NAME;

-- 27c. D_Shared_Item 新增 DESCRIPTION 列：应返回 1 行；NULLABLE='Y'、
--      CHAR_USED='C'、CHAR_LENGTH=200（实例为 BYTE 语义，须显式 CHAR 长度，
--      同 013/017/018/019 迁移先例）。
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE,
       CHAR_USED, CHAR_LENGTH
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'D_SHARED_ITEM'
  AND COLUMN_NAME = 'DESCRIPTION';

-- 27d. D_Asset_Warning 预警约束（状态/动作/完成一致性）：应返回 3 行，
--      CONSTRAINT_TYPE='C'。
SELECT TABLE_NAME, CONSTRAINT_NAME, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME IN ('CK_D_ASSET_WARNING_STATUS',
                          'CK_D_ASSET_WARNING_ACTION',
                          'CK_D_ASSET_WARNING_DONE')
ORDER BY CONSTRAINT_NAME;

-- 28. 检查迁移 030 的 TokenVersion 和 IsFirstLogin 列（编号可能变更）
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, NULLABLE
FROM USER_TAB_COLUMNS
WHERE (TABLE_NAME = 'D_ADMIN' AND COLUMN_NAME = 'TOKEN_VERSION')
   OR (TABLE_NAME = 'D_USER_ACCOUNT' AND COLUMN_NAME = 'IS_FIRST_LOGIN')
ORDER BY TABLE_NAME, COLUMN_NAME;

-- 29. 检查迁移 031 的 D_Audit_Event 主键序列与触发器
--     （C4 执行现场 ORA-01400 修复：审计表主键此前无生成器）。
--     序列 1 行；触发器 1 行。
SELECT SEQUENCE_NAME FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'SEQ_D_AUDIT_EVENT_ID';

SELECT TRIGGER_NAME, STATUS FROM USER_TRIGGERS
WHERE TRIGGER_NAME = 'TRG_D_AUDIT_EVENT_ID_BI';

-- 30. 检查迁移 032 的 CK_D_ADMIN_ROLE 值集已纳入"辅导员"（ADR-0007）。
--     迁移前约束为三值集（楼长/维修员/超级管理员），辅导员在 D_Admin 落库时
--     会被 ORA-02290 拦截；本段应返回 1 行，且 SEARCH_CONDITION 含"辅导员"。
SELECT CONSTRAINT_NAME, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'CK_D_ADMIN_ROLE'
  AND INSTR(SEARCH_CONDITION, '辅导员') > 0;
