-- 扩展表结构检查脚本。
-- 请在同一个 Oracle schema 中先执行
-- ddl/foundation/001_create_tables.sql 和 ddl/extensions/010_extension_tables.sql。

-- 1. 期望扩展表数量为 23 张。
SELECT COUNT(*) AS ACTUAL_EXTENSION_TABLE_COUNT
FROM USER_TABLES
WHERE TABLE_NAME IN (
    'D_FEE_DETAIL', 'D_WALLET_ACCOUNT', 'D_WALLET_LOG',
    'D_FEE_DEDUCTION_ATTEMPT', 'D_CREDIT_ACCOUNT', 'D_CREDIT_LOG',
    'D_SHARED_ITEM', 'D_ITEM_LOAN', 'D_FACILITY', 'D_FACILITY_BOOKING',
    'D_CLEANING_TASK', 'D_REPAIR_MATERIAL', 'D_REPAIR_MATERIAL_USAGE',
    'D_REPAIR_ATTACHMENT', 'D_USER_ACCOUNT', 'D_NOTIFICATION',
    'D_VISITOR_AUTHORIZATION', 'D_AUDIT_EVENT', 'D_ROOM_VOTE',
    'D_ROOM_VOTE_RESPONSE', 'D_CHECKOUT_LOG', 'D_NOTICE_DISPLAY',
    'D_HYGIENE_COMMENT'
);

-- 2. 检查缺失的扩展表：本查询应无返回行。
WITH EXPECTED_TABLES (TABLE_NAME) AS (
    SELECT 'D_FEE_DETAIL' FROM DUAL UNION ALL
    SELECT 'D_WALLET_ACCOUNT' FROM DUAL UNION ALL
    SELECT 'D_WALLET_LOG' FROM DUAL UNION ALL
    SELECT 'D_FEE_DEDUCTION_ATTEMPT' FROM DUAL UNION ALL
    SELECT 'D_CREDIT_ACCOUNT' FROM DUAL UNION ALL
    SELECT 'D_CREDIT_LOG' FROM DUAL UNION ALL
    SELECT 'D_SHARED_ITEM' FROM DUAL UNION ALL
    SELECT 'D_ITEM_LOAN' FROM DUAL UNION ALL
    SELECT 'D_FACILITY' FROM DUAL UNION ALL
    SELECT 'D_FACILITY_BOOKING' FROM DUAL UNION ALL
    SELECT 'D_CLEANING_TASK' FROM DUAL UNION ALL
    SELECT 'D_REPAIR_MATERIAL' FROM DUAL UNION ALL
    SELECT 'D_REPAIR_MATERIAL_USAGE' FROM DUAL UNION ALL
    SELECT 'D_REPAIR_ATTACHMENT' FROM DUAL UNION ALL
    SELECT 'D_USER_ACCOUNT' FROM DUAL UNION ALL
    SELECT 'D_NOTIFICATION' FROM DUAL UNION ALL
    SELECT 'D_VISITOR_AUTHORIZATION' FROM DUAL UNION ALL
    SELECT 'D_AUDIT_EVENT' FROM DUAL UNION ALL
    SELECT 'D_ROOM_VOTE' FROM DUAL UNION ALL
    SELECT 'D_ROOM_VOTE_RESPONSE' FROM DUAL UNION ALL
    SELECT 'D_CHECKOUT_LOG' FROM DUAL UNION ALL
    SELECT 'D_NOTICE_DISPLAY' FROM DUAL UNION ALL
    SELECT 'D_HYGIENE_COMMENT' FROM DUAL
)
SELECT TABLE_NAME
FROM EXPECTED_TABLES
MINUS
SELECT TABLE_NAME
FROM USER_TABLES;

-- 3. 检查范围裁决中明确排除的表：本查询应无返回行。
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN (
    'D_FACILITY_USAGE', 'D_REPAIR_SLA_EVENT', 'D_ROLE',
    'D_NOTIFICATION_RECIPIENT', 'D_FEE_ADJUSTMENT'
);

-- 4. 检查关键字段及其可空性，确认关键关联路径完整且必要字段为 NOT NULL。
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION,
       DATA_SCALE, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME IN (
    'D_FEE_DETAIL', 'D_WALLET_ACCOUNT', 'D_WALLET_LOG',
    'D_FEE_DEDUCTION_ATTEMPT', 'D_CREDIT_ACCOUNT', 'D_CREDIT_LOG',
    'D_SHARED_ITEM', 'D_ITEM_LOAN', 'D_FACILITY', 'D_FACILITY_BOOKING',
    'D_CLEANING_TASK', 'D_REPAIR_MATERIAL', 'D_REPAIR_MATERIAL_USAGE',
    'D_REPAIR_ATTACHMENT', 'D_USER_ACCOUNT', 'D_NOTIFICATION',
    'D_VISITOR_AUTHORIZATION', 'D_AUDIT_EVENT', 'D_ROOM_VOTE',
    'D_ROOM_VOTE_RESPONSE', 'D_CHECKOUT_LOG', 'D_NOTICE_DISPLAY',
    'D_HYGIENE_COMMENT'
)
AND COLUMN_NAME IN (
    'DETAIL_ID', 'FEE_ID', 'STUDENT_ID', 'ROOM_ID', 'WATER_SHARE',
    'POWER_SHARE', 'STAY_DAYS', 'TOTAL_DAYS', 'BILL_TYPE', 'IS_PAID',
    'BALANCE', 'LOG_ID', 'AMOUNT', 'TRANSACTION_TYPE', 'BEFORE_BALANCE',
    'AFTER_BALANCE', 'IDEMPOTENCY_KEY', 'ATTEMPT_ID', 'ATTEMPT_NO',
    'ATTEMPT_TIME', 'RESULT', 'CURRENT_SCORE', 'UPDATED_TIME',
    'SCORE_CHANGE', 'REASON', 'EVENT_KEY', 'ITEM_ID', 'ITEM_NAME',
    'BUILDING_ID', 'TOTAL_QTY', 'AVAILABLE_QTY', 'LOAN_ID', 'BORROW_TIME',
    'DUE_TIME', 'RETURN_TIME', 'FACILITY_ID', 'FACILITY_CODE',
    'FACILITY_TYPE', 'BOOKING_ID', 'CREATE_TIME', 'START_TIME', 'END_TIME',
    'TRIGGER_COUNT', 'STATUS', 'COMPLETE_TIME', 'MATERIAL_ID',
    'MATERIAL_NAME', 'UNIT', 'STOCK_QTY', 'USAGE_ID', 'TICKET_ID',
    'QUANTITY', 'USE_TIME', 'ATTACHMENT_ID', 'STORAGE_REF', 'ORIGINAL_NAME',
    'CONTENT_TYPE', 'FILE_SIZE', 'ACCOUNT_ID', 'LOGIN_NAME', 'PASSWORD_HASH',
    'ACCOUNT_STATUS', 'ADMIN_ID', 'NOTIFICATION_ID', 'RECIPIENT_ACCOUNT_ID',
    'TITLE', 'CONTENT', 'NOTIFICATION_TYPE', 'READ_TIME', 'AUTHORIZATION_ID',
    'VISITOR_NAME', 'VISIT_REASON', 'AUTHORIZATION_TOKEN', 'EXPIRES_TIME',
    'AUDIT_ID', 'ACTOR_ACCOUNT_ID', 'EVENT_TYPE', 'TARGET_TYPE', 'TARGET_ID',
    'EVENT_TIME', 'VOTE_ID', 'INITIATOR_STUDENT_ID', 'TOPIC', 'DEADLINE',
    'ELIGIBLE_COUNT', 'VOTE_TIME', 'CHOICE', 'REQUEST_TIME', 'RESULT_TIME',
    'FEE_CHECK', 'ITEM_CHECK', 'REJECT_REASON', 'NOTICE_ID', 'IS_PINNED',
    'PIN_TIME', 'RECORD_ID', 'COMMENT'
)
ORDER BY TABLE_NAME, COLUMN_ID;

-- 5. 检查扩展表约束是否全部启用且已验证。
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS, VALIDATED
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN (
    'D_FEE_DETAIL', 'D_WALLET_ACCOUNT', 'D_WALLET_LOG',
    'D_FEE_DEDUCTION_ATTEMPT', 'D_CREDIT_ACCOUNT', 'D_CREDIT_LOG',
    'D_SHARED_ITEM', 'D_ITEM_LOAN', 'D_FACILITY', 'D_FACILITY_BOOKING',
    'D_CLEANING_TASK', 'D_REPAIR_MATERIAL', 'D_REPAIR_MATERIAL_USAGE',
    'D_REPAIR_ATTACHMENT', 'D_USER_ACCOUNT', 'D_NOTIFICATION',
    'D_VISITOR_AUTHORIZATION', 'D_AUDIT_EVENT', 'D_ROOM_VOTE',
    'D_ROOM_VOTE_RESPONSE', 'D_CHECKOUT_LOG', 'D_NOTICE_DISPLAY',
    'D_HYGIENE_COMMENT'
)
AND (STATUS <> 'ENABLED' OR VALIDATED <> 'VALIDATED')
ORDER BY TABLE_NAME, CONSTRAINT_NAME;

-- 6. 按约束类型统计扩展表约束数量。
SELECT CONSTRAINT_TYPE, COUNT(*) AS CONSTRAINT_COUNT
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN (
    'D_FEE_DETAIL', 'D_WALLET_ACCOUNT', 'D_WALLET_LOG',
    'D_FEE_DEDUCTION_ATTEMPT', 'D_CREDIT_ACCOUNT', 'D_CREDIT_LOG',
    'D_SHARED_ITEM', 'D_ITEM_LOAN', 'D_FACILITY', 'D_FACILITY_BOOKING',
    'D_CLEANING_TASK', 'D_REPAIR_MATERIAL', 'D_REPAIR_MATERIAL_USAGE',
    'D_REPAIR_ATTACHMENT', 'D_USER_ACCOUNT', 'D_NOTIFICATION',
    'D_VISITOR_AUTHORIZATION', 'D_AUDIT_EVENT', 'D_ROOM_VOTE',
    'D_ROOM_VOTE_RESPONSE', 'D_CHECKOUT_LOG', 'D_NOTICE_DISPLAY',
    'D_HYGIENE_COMMENT'
)
GROUP BY CONSTRAINT_TYPE
ORDER BY CONSTRAINT_TYPE;

-- 7. 检查本方案中明确采用的复合主键和复合唯一约束。
SELECT CONSTRAINT_NAME, TABLE_NAME, POSITION, COLUMN_NAME
FROM USER_CONS_COLUMNS
WHERE CONSTRAINT_NAME IN (
    'PK_D_ROOM_VOTE_RESP', 'UK_D_FEE_DED_ATT', 'UK_D_FACILITY_CODE',
    'UK_D_CLEANING_TRIGGER', 'UK_D_FEE_DETAIL'
)
ORDER BY CONSTRAINT_NAME, POSITION;

-- 8. 检查扩展表外键及其引用目标。
SELECT CHILD_CONSTRAINT.CONSTRAINT_NAME,
       CHILD.TABLE_NAME AS CHILD_TABLE,
       CHILD.COLUMN_NAME AS CHILD_COLUMN,
       PARENT.TABLE_NAME AS PARENT_TABLE,
       PARENT.COLUMN_NAME AS PARENT_COLUMN
FROM USER_CONS_COLUMNS CHILD
JOIN USER_CONSTRAINTS CHILD_CONSTRAINT
  ON CHILD.CONSTRAINT_NAME = CHILD_CONSTRAINT.CONSTRAINT_NAME
 AND CHILD.OWNER = CHILD_CONSTRAINT.OWNER
JOIN USER_CONS_COLUMNS PARENT
  ON CHILD_CONSTRAINT.R_CONSTRAINT_NAME = PARENT.CONSTRAINT_NAME
 AND CHILD_CONSTRAINT.R_OWNER = PARENT.OWNER
 AND CHILD.POSITION = PARENT.POSITION
WHERE CHILD_CONSTRAINT.CONSTRAINT_TYPE = 'R'
  AND CHILD.TABLE_NAME IN (
      'D_FEE_DETAIL', 'D_WALLET_ACCOUNT', 'D_WALLET_LOG',
      'D_FEE_DEDUCTION_ATTEMPT', 'D_CREDIT_ACCOUNT', 'D_CREDIT_LOG',
      'D_SHARED_ITEM', 'D_ITEM_LOAN', 'D_FACILITY', 'D_FACILITY_BOOKING',
      'D_CLEANING_TASK', 'D_REPAIR_MATERIAL', 'D_REPAIR_MATERIAL_USAGE',
      'D_REPAIR_ATTACHMENT', 'D_USER_ACCOUNT', 'D_NOTIFICATION',
      'D_VISITOR_AUTHORIZATION', 'D_AUDIT_EVENT', 'D_ROOM_VOTE',
      'D_ROOM_VOTE_RESPONSE', 'D_CHECKOUT_LOG', 'D_NOTICE_DISPLAY',
      'D_HYGIENE_COMMENT'
  )
ORDER BY CHILD.TABLE_NAME, CHILD_CONSTRAINT.CONSTRAINT_NAME, CHILD.POSITION;

-- 9. 检查账号身份互斥绑定约束、公告置顶约束和通知类型枚举约束是否存在
--    （CK_D_NOTIFICATION_TYPE 来自迁移脚本 011）。
SELECT CONSTRAINT_NAME, SEARCH_CONDITION_VC
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME IN ('CK_D_USER_STATUS', 'CK_D_USER_IDENTITY',
                          'CK_D_NOTICE_DISPLAY_PIN', 'CK_D_NOTIFICATION_TYPE')
ORDER BY CONSTRAINT_NAME;

-- 10. 检查部分唯一索引存在且有效（退宿清算与设施预约并发兜底）。
SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS, STATUS
FROM USER_INDEXES
WHERE INDEX_NAME IN ('UK_D_CHECKOUT_ACTIVE', 'UK_D_FACILITY_BOOK_ACTIVE')
ORDER BY INDEX_NAME;

-- 11. 检查迁移 012 的通知主键序列、触发器和收件人索引（D_Notification 落库依赖）。
SELECT SEQUENCE_NAME FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'SEQ_D_NOTIFICATION_ID';
SELECT TRIGGER_NAME, STATUS FROM USER_TRIGGERS
WHERE TRIGGER_NAME = 'TRG_D_NOTIFICATION_ID_BI';
SELECT INDEX_NAME, TABLE_NAME, STATUS FROM USER_INDEXES
WHERE INDEX_NAME = 'IDX_D_NOTIFICATION_RECIPIENT';

-- 12. 检查迁移 014 的信用分序列、触发器、稳定排序索引和字符长度语义。
SELECT SEQUENCE_NAME
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'SEQ_D_CREDIT_LOG_ID';

SELECT TRIGGER_NAME, STATUS
FROM USER_TRIGGERS
WHERE TRIGGER_NAME = 'TRG_D_CREDIT_LOG_ID_BI';

SELECT INDEX_NAME, COLUMN_POSITION, COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE INDEX_NAME = 'IDX_D_CREDIT_LOG_STUDENT_TIME'
ORDER BY COLUMN_POSITION;

SELECT COLUMN_NAME, CHAR_USED, CHAR_LENGTH
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'D_CREDIT_LOG'
  AND ((COLUMN_NAME = 'REASON' AND CHAR_USED = 'C' AND CHAR_LENGTH = 200)
    OR (COLUMN_NAME = 'EVENT_KEY' AND CHAR_USED = 'C' AND CHAR_LENGTH = 100))
ORDER BY COLUMN_NAME;

-- 13. 检查 010 新增的主键序列与触发器（D_Facility / D_Notice / D_Notice_Display）。
--     每段 SELECT 均应返回 1 行；缺任意一个对象说明 010 未完整执行。
SELECT SEQUENCE_NAME FROM USER_SEQUENCES
WHERE SEQUENCE_NAME IN ('SEQ_D_FACILITY_ID', 'SEQ_D_NOTICE_ID', 'SEQ_D_NOTICE_DISPLAY_PK')
ORDER BY SEQUENCE_NAME;

SELECT TRIGGER_NAME, STATUS FROM USER_TRIGGERS
WHERE TRIGGER_NAME IN ('TRG_D_FACILITY_ID_BI', 'TRG_D_NOTICE_ID_BI', 'TRG_D_NOTICE_DISPLAY_PK_BI')
ORDER BY TRIGGER_NAME;
