-- 基础表结构检查脚本。
-- 请在同一个 Oracle 用户下执行 001_create_tables.sql 后再执行本脚本。

-- 1. 期望表数量为 20 张。
SELECT COUNT(*) AS ACTUAL_TABLE_COUNT
FROM USER_TABLES
WHERE TABLE_NAME IN (
    'D_COLLEGE', 'D_BUILDING', 'D_ADMIN', 'D_MAJOR', 'D_ROOM',
    'D_NOTICE', 'D_VISITOR_LOG', 'D_STUDENT', 'D_ASSET',
    'D_UTILITY_FEE', 'D_HYGIENE_RECORD', 'D_WATER_ORDER',
    'D_BED_ALLOCATION', 'D_REPAIR_TICKET', 'D_REPAIR_LOG',
    'D_LATE_ENTRY', 'D_ACCESS_LOG', 'D_LEAVE_APPLICATION',
    'D_PARCEL_RECORD', 'D_VIOLATION_RECORD'
);

-- 2. 检查缺失的期望表：本查询应无返回结果。
WITH EXPECTED_TABLES (TABLE_NAME) AS (
    SELECT 'D_COLLEGE' FROM DUAL UNION ALL
    SELECT 'D_BUILDING' FROM DUAL UNION ALL
    SELECT 'D_ADMIN' FROM DUAL UNION ALL
    SELECT 'D_MAJOR' FROM DUAL UNION ALL
    SELECT 'D_ROOM' FROM DUAL UNION ALL
    SELECT 'D_NOTICE' FROM DUAL UNION ALL
    SELECT 'D_VISITOR_LOG' FROM DUAL UNION ALL
    SELECT 'D_STUDENT' FROM DUAL UNION ALL
    SELECT 'D_ASSET' FROM DUAL UNION ALL
    SELECT 'D_UTILITY_FEE' FROM DUAL UNION ALL
    SELECT 'D_HYGIENE_RECORD' FROM DUAL UNION ALL
    SELECT 'D_WATER_ORDER' FROM DUAL UNION ALL
    SELECT 'D_BED_ALLOCATION' FROM DUAL UNION ALL
    SELECT 'D_REPAIR_TICKET' FROM DUAL UNION ALL
    SELECT 'D_REPAIR_LOG' FROM DUAL UNION ALL
    SELECT 'D_LATE_ENTRY' FROM DUAL UNION ALL
    SELECT 'D_ACCESS_LOG' FROM DUAL UNION ALL
    SELECT 'D_LEAVE_APPLICATION' FROM DUAL UNION ALL
    SELECT 'D_PARCEL_RECORD' FROM DUAL UNION ALL
    SELECT 'D_VIOLATION_RECORD' FROM DUAL
)
SELECT TABLE_NAME
FROM EXPECTED_TABLES
MINUS
SELECT TABLE_NAME
FROM USER_TABLES;

-- 3. 检查已经确认的 5 个字段：以下查询应返回全部字段。
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION,
       DATA_SCALE, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE (TABLE_NAME, COLUMN_NAME) IN (
    ('D_ROOM', 'POWER_STATUS'),
    ('D_REPAIR_TICKET', 'SLA_LEVEL'),
    ('D_REPAIR_TICKET', 'DEADLINE'),
    ('D_REPAIR_TICKET', 'ASSIGNED_TO'),
    ('D_ADMIN', 'BUILDING_ID')
)
ORDER BY TABLE_NAME, COLUMN_NAME;

-- 4. 检查基础表不包含 D_Student.Balance：本查询应无返回结果。
SELECT TABLE_NAME, COLUMN_NAME
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'D_STUDENT'
  AND COLUMN_NAME = 'BALANCE';

-- 5. 检查主键、外键、唯一约束和检查约束。
SELECT CONSTRAINT_NAME, TABLE_NAME, CONSTRAINT_TYPE, STATUS
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME IN (
    'PK_D_COLLEGE', 'PK_D_BUILDING', 'PK_D_ADMIN', 'PK_D_MAJOR',
    'PK_D_ROOM', 'PK_D_NOTICE', 'PK_D_VISITOR_LOG', 'PK_D_STUDENT',
    'PK_D_ASSET', 'PK_D_UTILITY_FEE', 'PK_D_HYGIENE_RECORD',
    'PK_D_WATER_ORDER', 'PK_D_BED_ALLOCATION', 'PK_D_REPAIR_TICKET',
    'PK_D_REPAIR_LOG', 'PK_D_LATE_ENTRY', 'PK_D_ACCESS_LOG',
    'PK_D_LEAVE_APPLICATION', 'PK_D_PARCEL_RECORD',
    'PK_D_VIOLATION_RECORD', 'FK_D_ADMIN_BUILDING',
    'FK_D_REPAIR_TICKET_ASSIGNED_ADMIN', 'CK_D_ROOM_POWER_STATUS',
    'CK_D_REPAIR_TICKET_SLA_LEVEL', 'UK_D_REPAIR_LOG_TICKET'
)
ORDER BY TABLE_NAME, CONSTRAINT_TYPE, CONSTRAINT_NAME;

-- 6. 检查已确认字段中的外键引用关系。
SELECT CHILD.TABLE_NAME AS CHILD_TABLE,
       CHILD.COLUMN_NAME AS CHILD_COLUMN,
       PARENT.TABLE_NAME AS PARENT_TABLE,
       PARENT.COLUMN_NAME AS PARENT_COLUMN,
       CHILD_CONSTRAINT.CONSTRAINT_NAME
FROM USER_CONS_COLUMNS CHILD
JOIN USER_CONSTRAINTS CHILD_CONSTRAINT
  ON CHILD.CONSTRAINT_NAME = CHILD_CONSTRAINT.CONSTRAINT_NAME
 AND CHILD.OWNER = CHILD_CONSTRAINT.OWNER
JOIN USER_CONS_COLUMNS PARENT
  ON CHILD_CONSTRAINT.R_CONSTRAINT_NAME = PARENT.CONSTRAINT_NAME
 AND CHILD_CONSTRAINT.R_OWNER = PARENT.OWNER
WHERE CHILD_CONSTRAINT.CONSTRAINT_NAME IN (
    'FK_D_ADMIN_BUILDING',
    'FK_D_REPAIR_TICKET_ASSIGNED_ADMIN'
)
ORDER BY CHILD.TABLE_NAME, CHILD.COLUMN_NAME;
