// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TemplateDormApi.Data;

#nullable disable

namespace TemplateDormApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814085058_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TemplateDormApi.Models.Admin", b =>
                {
                    b.Property<string>("AdminId")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ADMIN_ID");

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ADMIN_NAME");

                    b.Property<long?>("BuildingId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("BUILDING_ID");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PHONE");

                    b.Property<string>("RoleLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ROLE_LEVEL");

                    b.HasKey("AdminId");

                    b.ToTable("D_ADMIN", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ASSET_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetId"));

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ASSET_NAME");

                    b.Property<int?>("Quantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITY");

                    b.Property<int?>("RoomId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ROOM_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.HasKey("AssetId");

                    b.HasIndex("RoomId");

                    b.ToTable("D_ASSET", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.BedAllocation", b =>
                {
                    b.Property<long>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ALLOCATION_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AllocationId"));

                    b.Property<int>("BedNo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BED_NO");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CHECKIN_DATE");

                    b.Property<DateTime?>("CheckOutDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CHECKOUT_DATE");

                    b.Property<long?>("RoomId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ROOM_ID");

                    b.Property<string>("StudentId")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STUDENT_ID");

                    b.HasKey("AllocationId");

                    b.ToTable("D_BED_ALLOCATION", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BUILDING_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuildingId"));

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("BUILDING_NAME");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("BUILDING_TYPE");

                    b.Property<int?>("FloorCount")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TOTAL_FLOORS");

                    b.HasKey("BuildingId");

                    b.ToTable("D_BUILDING", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.CreditAccount", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STUDENT_ID");

                    b.Property<int>("CurrentScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(100)
                        .HasColumnName("CURRENT_SCORE");

                    b.Property<DateTime>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_TIME")
                        .HasDefaultValueSql("SYSDATE");

                    b.HasKey("StudentId");

                    b.ToTable("D_CREDIT_ACCOUNT", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.CreditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LOG_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EVENT_KEY");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("REASON");

                    b.Property<int>("ScoreChange")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SCORE_CHANGE");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STUDENT_ID");

                    b.HasKey("LogId");

                    b.HasIndex("StudentId");

                    b.ToTable("D_CREDIT_LOG", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.Facility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FACILITY_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityId"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BUILDING_ID");

                    b.Property<string>("FacilityCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("FACILITY_CODE");

                    b.Property<string>("FacilityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("FACILITY_TYPE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("STATUS");

                    b.HasKey("FacilityId");

                    b.HasIndex("BuildingId");

                    b.ToTable("D_FACILITY", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.FacilityBooking", b =>
                {
                    b.Property<long>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("BOOKING_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BookingId"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATE_TIME");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("END_TIME");

                    b.Property<long>("FacilityId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("FACILITY_ID");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("START_TIME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("STATUS");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STUDENT_ID");

                    b.HasKey("BookingId");

                    b.ToTable("D_FACILITY_BOOKING", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.FeeDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Detail_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("BillType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Bill_Type");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("Create_Time");

                    b.Property<int>("FeeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Fee_ID");

                    b.Property<string>("IsPaid")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Is_Paid");

                    b.Property<decimal>("PowerShare")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("Power_Share");

                    b.Property<int>("RoomId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Room_ID");

                    b.Property<int>("StayDays")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Stay_Days");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Student_ID");

                    b.Property<int>("TotalDays")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Total_Days");

                    b.Property<decimal>("WaterShare")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("Water_Share");

                    b.HasKey("DetailId");

                    b.ToTable("D_Fee_Detail", "DORM_OPER");
                });

            modelBuilder.Entity("TemplateDormApi.Models.HygieneComment", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("RECORD_ID");

                    b.Property<string>("CommentText")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("COMMENT");

                    b.HasKey("RecordId");

                    b.ToTable("D_HYGIENE_COMMENT", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.HygieneRecord", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("RECORD_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecordId"));

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CHECK_DATE");

                    b.Property<string>("InspectorId")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("INSPECTOR_ID");

                    b.Property<long?>("RoomId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ROOM_ID");

                    b.Property<decimal>("Score")
                        .HasPrecision(4, 1)
                        .HasColumnType("DECIMAL(4,1)")
                        .HasColumnName("SCORE");

                    b.HasKey("RecordId");

                    b.ToTable("D_HYGIENE_RECORD", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.ItemLoan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LOAN_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"));

                    b.Property<DateTime>("BorrowTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("BORROW_TIME");

                    b.Property<DateTime>("DueTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DUE_TIME");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("IDEMPOTENCY_KEY");

                    b.Property<int>("ItemId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ITEM_ID");

                    b.Property<DateTime?>("ReturnTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("RETURN_TIME");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STUDENT_ID");

                    b.HasKey("LoanId");

                    b.ToTable("D_ITEM_LOAN", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.LateEntry", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("RECORD_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecordId"));

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("REASON");

                    b.Property<DateTime>("ReturnTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("RETURN_TIME");

                    b.Property<string>("StudentId")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STUDENT_ID");

                    b.HasKey("RecordId");

                    b.ToTable("D_LATE_ENTRY", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.Notice", b =>
                {
                    b.Property<int>("NoticeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NOTICE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoticeId"));

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ADMIN_ID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("CONTENT");

                    b.Property<DateTime>("PublishTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PUBLISH_TIME");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TITLE");

                    b.HasKey("NoticeId");

                    b.ToTable("D_NOTICE", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.NoticeDisplay", b =>
                {
                    b.Property<int>("NoticeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NOTICE_ID");

                    b.Property<string>("IsPinned")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("IS_PINNED");

                    b.Property<DateTime?>("PinTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PIN_TIME");

                    b.HasKey("NoticeId");

                    b.ToTable("D_NOTICE_DISPLAY", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NOTIFICATION_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("CONTENT");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NOTIFICATION_TYPE");

                    b.Property<DateTime?>("ReadTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("READ_TIME");

                    b.Property<int>("RecipientAccountId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RECIPIENT_ACCOUNT_ID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TITLE");

                    b.HasKey("NotificationId");

                    b.HasIndex("RecipientAccountId");

                    b.ToTable("D_NOTIFICATION", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.RepairAttachment", b =>
                {
                    b.Property<long>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ATTACHMENT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AttachmentId"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CONTENT_TYPE");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<long?>("FileSize")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("FILE_SIZE");

                    b.Property<string>("OriginalName")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("ORIGINAL_NAME");

                    b.Property<string>("StorageRef")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("STORAGE_REF");

                    b.Property<long>("TicketId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("TICKET_ID");

                    b.HasKey("AttachmentId");

                    b.HasIndex("TicketId");

                    b.ToTable("D_REPAIR_ATTACHMENT", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.RepairLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LOG_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("AdminId")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ADMIN_ID");

                    b.Property<string>("ProcessDescription")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("PROCESS_DESC");

                    b.Property<DateTime>("ResolveTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("RESOLVE_TIME");

                    b.Property<long?>("TicketId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("TICKET_ID");

                    b.HasKey("LogId");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasFilter("\"TICKET_ID\" IS NOT NULL");

                    b.ToTable("D_REPAIR_LOG", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.RepairMaterial", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MATERIAL_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MATERIAL_NAME");

                    b.Property<int>("StockQty")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STOCK_QTY");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("UNIT");

                    b.HasKey("MaterialId");

                    b.ToTable("D_REPAIR_MATERIAL", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.RepairMaterialUsage", b =>
                {
                    b.Property<int>("UsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USAGE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsageId"));

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("IDEMPOTENCY_KEY");

                    b.Property<int>("MaterialId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MATERIAL_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITY");

                    b.Property<int>("TicketId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TICKET_ID");

                    b.Property<DateTime>("UseTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("USE_TIME");

                    b.HasKey("UsageId");

                    b.ToTable("D_REPAIR_MATERIAL_USAGE", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.RepairTicket", b =>
                {
                    b.Property<long>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("TICKET_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TicketId"));

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ASSIGNED_TO");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DEADLINE");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("ISSUE_DESC");

                    b.Property<long?>("RoomId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ROOM_ID");

                    b.Property<string>("SlaLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("SLA_LEVEL");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("StudentId")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STUDENT_ID");

                    b.Property<DateTime>("SubmitTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("SUBMIT_TIME");

                    b.HasKey("TicketId");

                    b.ToTable("D_REPAIR_TICKET", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ROOM_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int?>("BuildingId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BUILDING_ID");

                    b.Property<int?>("Capacity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CAPACITY");

                    b.Property<int?>("Floor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FLOOR");

                    b.Property<int?>("Occupancy")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("OCCUPANCY");

                    b.Property<string>("PowerStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("POWER_STATUS");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ROOM_NUMBER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("STATUS");

                    b.HasKey("RoomId");

                    b.HasIndex("BuildingId");

                    b.ToTable("D_ROOM", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.SharedItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ITEM_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("AvailableQty")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AVAILABLE_QTY");

                    b.Property<int>("BuildingId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BUILDING_ID");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ITEM_NAME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("STATUS");

                    b.Property<int>("TotalQty")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TOTAL_QTY");

                    b.HasKey("ItemId");

                    b.ToTable("D_SHARED_ITEM", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STUDENT_ID");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("GENDER");

                    b.Property<long?>("MajorId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("MAJOR_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PHONE");

                    b.HasKey("StudentId");

                    b.ToTable("D_STUDENT", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.UserAccount", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ACCOUNT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACCOUNT_STATUS");

                    b.Property<string>("AdminId")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ADMIN_ID");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("LOGIN_NAME");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<string>("StudentId")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STUDENT_ID");

                    b.HasKey("AccountId");

                    b.ToTable("D_USER_ACCOUNT", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.UtilityFee", b =>
                {
                    b.Property<long>("FeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("FEE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FeeId"));

                    b.Property<string>("IsPaid")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("IS_PAID");

                    b.Property<decimal?>("PowerFee")
                        .HasPrecision(8, 2)
                        .HasColumnType("DECIMAL(8,2)")
                        .HasColumnName("POWER_FEE");

                    b.Property<string>("PublishStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("PUBLISH_STATUS");

                    b.Property<long>("RoomId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ROOM_ID");

                    b.Property<decimal?>("WaterFee")
                        .HasPrecision(8, 2)
                        .HasColumnType("DECIMAL(8,2)")
                        .HasColumnName("WATER_FEE");

                    b.Property<string>("YearMonth")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("YEAR_MONTH");

                    b.HasKey("FeeId");

                    b.ToTable("D_UTILITY_FEE", (string)null);
                });

            modelBuilder.Entity("TemplateDormApi.Models.WalletAccount", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("Student_ID");

                    b.Property<decimal>("Balance")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("Balance");

                    b.HasKey("StudentId");

                    b.ToTable("D_Wallet_Account", "DORM_OPER");
                });

            modelBuilder.Entity("TemplateDormApi.Models.WalletLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Log_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<decimal>("AfterBalance")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("After_Balance");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("Amount");

                    b.Property<decimal>("BeforeBalance")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("Before_Balance");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("Create_Time");

                    b.Property<int?>("DetailId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Detail_ID");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Idempotency_Key");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Student_ID");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Transaction_Type");

                    b.HasKey("LogId");

                    b.ToTable("D_Wallet_Log", "DORM_OPER");
                });

            modelBuilder.Entity("TemplateDormApi.Models.Asset", b =>
                {
                    b.HasOne("TemplateDormApi.Models.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("TemplateDormApi.Models.CreditLog", b =>
                {
                    b.HasOne("TemplateDormApi.Models.CreditAccount", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_D_CREDIT_LOG_ACCOUNT");
                });

            modelBuilder.Entity("TemplateDormApi.Models.Facility", b =>
                {
                    b.HasOne("TemplateDormApi.Models.Building", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_D_FACILITY_BUILDING");
                });

            modelBuilder.Entity("TemplateDormApi.Models.HygieneComment", b =>
                {
                    b.HasOne("TemplateDormApi.Models.HygieneRecord", "Record")
                        .WithOne("Comment")
                        .HasForeignKey("TemplateDormApi.Models.HygieneComment", "RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("TemplateDormApi.Models.NoticeDisplay", b =>
                {
                    b.HasOne("TemplateDormApi.Models.Notice", "Notice")
                        .WithOne("Display")
                        .HasForeignKey("TemplateDormApi.Models.NoticeDisplay", "NoticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notice");
                });

            modelBuilder.Entity("TemplateDormApi.Models.Notification", b =>
                {
                    b.HasOne("TemplateDormApi.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("RecipientAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_D_NOTIFICATION_ACCOUNT");
                });

            modelBuilder.Entity("TemplateDormApi.Models.RepairAttachment", b =>
                {
                    b.HasOne("TemplateDormApi.Models.RepairTicket", null)
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TemplateDormApi.Models.RepairLog", b =>
                {
                    b.HasOne("TemplateDormApi.Models.RepairTicket", null)
                        .WithOne("Log")
                        .HasForeignKey("TemplateDormApi.Models.RepairLog", "TicketId");
                });

            modelBuilder.Entity("TemplateDormApi.Models.Room", b =>
                {
                    b.HasOne("TemplateDormApi.Models.Building", null)
                        .WithMany()
                        .HasForeignKey("BuildingId");
                });

            modelBuilder.Entity("TemplateDormApi.Models.HygieneRecord", b =>
                {
                    b.Navigation("Comment");
                });

            modelBuilder.Entity("TemplateDormApi.Models.Notice", b =>
                {
                    b.Navigation("Display");
                });

            modelBuilder.Entity("TemplateDormApi.Models.RepairTicket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Log");
                });
#pragma warning restore 612, 618
        }
    }
}
