using Microsoft.EntityFrameworkCore;
using TemplateDormApi.Data;
using TemplateDormApi.Models;

namespace TemplateDormApi.Tests;

/// <summary>
/// 迁移 023 序列+触发器主键回填（EF 侧 ValueGeneratedOnAdd 配置回归）：
/// 三张表不显式赋主键也能拿到生成值。InMemory 只能验证"生成值 &gt; 0"；
/// 真库触发器回填（WHEN NEW IS NULL / MAXVALUE 上限 / 显式值兼容）由兰皓衍执行迁移 verify 留证。
/// </summary>
public class Migration023KeyGenerationTests
{
    private static AppDbContext CreateContext()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>()
            .UseInMemoryDatabase($"migration023-tests-{Guid.NewGuid():N}")
            .Options;
        return new AppDbContext(options);
    }

    [Fact]
    public async Task BedAllocation_PrimaryKeyAutoGenerated_WhenNotSet()
    {
        await using var context = CreateContext();

        var entity = new BedAllocation
        {
            StudentId = "S001",
            RoomId = 101,
            BedNo = 1,
            CheckInDate = new DateTime(2026, 8, 1)
        };
        await context.BedAllocations.AddAsync(entity);
        await context.SaveChangesAsync();

        Assert.True(entity.AllocationId > 0,
            "迁移 023：ALLOCATION_ID 由 SEQ_D_BED_ALLOCATION_ID + 触发器生成（EF 侧 ValueGeneratedOnAdd）");
    }

    [Fact]
    public async Task CheckoutLog_PrimaryKeyAutoGenerated_WhenNotSet()
    {
        await using var context = CreateContext();

        var entity = new CheckoutLog
        {
            AllocationId = 1,
            RequestTime = DateTime.Now,
            Status = "待清算"
        };
        await context.CheckoutLogs.AddAsync(entity);
        await context.SaveChangesAsync();

        Assert.True(entity.LogId > 0,
            "迁移 023：LOG_ID 由 SEQ_D_CHECKOUT_LOG_ID + 触发器生成（EF 侧 ValueGeneratedOnAdd）");
    }

    [Fact]
    public async Task LeaveApplication_PrimaryKeyAutoGenerated_WhenNotSet()
    {
        await using var context = CreateContext();

        var entity = new LeaveApplication
        {
            StudentId = "S001",
            LeaveDate = new DateTime(2026, 8, 10),
            ReturnDate = new DateTime(2026, 8, 20),
            Destination = "北京",
            Status = "待批"
        };
        await context.LeaveApplications.AddAsync(entity);
        await context.SaveChangesAsync();

        Assert.True(entity.ApplyId > 0,
            "迁移 023：APPLY_ID 由 SEQ_D_LEAVE_APPLICATION_ID + 触发器生成（EF 侧 ValueGeneratedOnAdd）");
    }
}
